### ISSUE TITLE
Question: Google Finance API and Scipy

### ISSUE THREAD

**Issue by pramanadiputra** [mcdallas/wallstreet#10]
Hi mcdallas, 

I have a question, on the description there's statement "provided from the Google Finance API"
Isn't the Google Finance API has been shut down? 

is this library still work? 

Thank you :)

**Comment by mcdallas** [comment]
@pramanadiputra Yes officialy it has been shut down. However there are some endpoints that still work and have no delay. For example http://finance.google.com/finance/info?q=AAPL

**Comment by pramanadiputra** [comment]
@mcdallas Thank You :), and I just touch Python for 1 week. And I don't understand what this mean 'Wallstreet requires Scipy, requests and bs4 (BeautifulSoup4). Requests and bs4 are installed for you when pip installing but you need to have Scipy pre-installed.' 

how to have Scipy pre-installed on Windows? It seems I have to download them and install them first?

**Comment by mcdallas** [comment]
```
pip install scipy
pip install wallstreet
```
This should get you everything you need. Alternatively you can install [Anaconda](https://www.continuum.io/downloads) which includes Scipy
