### ISSUE TITLE
Google Finance Change

### ISSUE THREAD

**Issue by rsmileyc** [mcdallas/wallstreet#18]
It appears that Google Finance has made another change in their API so Wallstreet is unable to find any stocks. I reloaded the Wallstreet module this morning but this didn't fix the issue.   Is a change in work for Wlalstreet?

**Comment by mcdallas** [comment]
Yes, I am going to have a look at it at some point. Probably this weekend

**Comment by rsmileyc** [comment]
The Wallstreet module is still not working.  Here is the error that I get: LookupError: Ticker symbol not found. Try adding the exchange parameter.

**Comment by mcdallas** [comment]
@rsmileyc the google api endpoint is gone and I couldn't find any replacement. If you find another one that we can use please post it here and I will use that.

**Comment by westonplatter** [comment]
@mcdallas IEX has free real time quotes for stocks (but not options or major indexes like SPX). https://iextrading.com/developer/docs/.

**Comment by reiven** [comment]
This is not working anymore, right?

**Comment by kannaiah** [comment]
Would Yahoo finance work?

**Comment by mcdallas** [comment]
Yes google was discontinued but yahoo still works. You need to use the source='yahoo' parameter

**Comment by kannaiah** [comment]
Thanks. With `source='yahoo'` does seem to work but only recent option quotes are in the data. Can't seem to get data for other expirations.
I tried finding documentation on API but no luck, do you have any idea?

**Comment by mcdallas** [comment]
Can you give an example with what data is missing? You should be able to access all the quotes that are accessible in https://finance.yahoo.com/

**Comment by kannaiah** [comment]
Sorry, I might have done something wrong, it seems to work.
