### ISSUE TITLE
LookupError: Ticker symbol not found. Try adding the exchange parameter

### ISSUE THREAD

**Issue by moongraber** [mcdallas/wallstreet#20]
Hi

this package seems very interesting, I tried using it with Stock with ticker MTCH

tried:
s = Stock('MTCH')

LookupError: Ticker symbol not found. Try adding the exchange parameter

s = Stock('MTCH',exchange="NASDAQ")

LookupError: Ticker symbol not found. Try adding the exchange parameter

s = Stock('MTCH',exchange="NASD")
LookupError: Ticker symbol not found. Try adding the exchange parameter

tried:
pip install --upgrade git+https://github.com/mcdallas/wallstreet.git

got the same error in all three cases

**Comment by mcdallas** [comment]
@moongraber unfortunately Google Finance API has being discontinued. The only way to use this module atm is to use the source='yahoo' parameter which makes it pull the prices from Yahoo Finance instead. Keep in mind that in some cases Yahoo Finance quotes are delayed by up to 15 minutes.

**Comment by moongraber** [comment]
ok thanks !
