### ISSUE TITLE
.HTTPError exception

### ISSUE THREAD

**Issue by Yachter** [mcdallas/wallstreet#23]
Hello there.

Calling by this:
`  opt_obj = Call('FB', d=17, m=4, y=2020 )`

causes next error and script halt:

> File "D:\WorkDir\script.py", line 62, in <module>
>   opt_obj = ('FB', d=17, m=4, y=2020 )
> File "с:\Program Files\Python38\Lib\site-packages\wallstreet\wallstreet.py", line 325, in __init__
>   super().__init__(quote, self.__class__.Option_type, **kw)
> File "с:\Program Files\Python38\Lib\site-packages\wallstreet\wallstreet.py", line 218, in __init__
>   self._yahoo(quote, d, m, y)
> File "с:\Program Files\Python38\Lib\site-packages\wallstreet\wallstreet.py", line 257, in _yahoo
>   r.raise_for_status()
> File "с:\Program Files\Python38\Lib\site-packages\requests\models.py", line 940, in raise_for_status
>   raise HTTPError(http_error_msg, response=self)
> 
> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://query2.finance.yahoo.com/v7/finance/options/FB?date=1587081600

I know, that's not because of your code, but need a solution.

Regards.

**Comment by mcdallas** [comment]
not much you can do if Yahoo finance is down since this is where we are getting the price info from
