### ISSUE TITLE
Index Option Quotes

### ISSUE THREAD

**Issue by HarryPublic** [mcdallas/wallstreet#3]
Were you ever able to get this to return Index Option Quotes?

For example: 
g=Call('INDEXSP:.INX', d=20, m=10, y=2016, strike=2150)

Tried d=20 as well as 21
Tried INDEXSP, SPX, INDEXCBOE:SPX and a few other variations, but could not get index option data.

One issue is that it will return the same error message "No options listed for this stock." even if the date is incorrect - but I guess that you get a JSON object without a list of valid options and it does not tell you whether the expiry is valid or not - so can not fix that easily.

However, knowing the codes to get this API to show option data for SPX, RUT, NDX and other major indices will be very helpful.

**Comment by baerrus** [comment]
THis code fetches option quotes from GoogleFinance, right? I have noticed that GF website does not show options chains for indeces like VIX, SPX etc.

How difficult would it be to attach yahoo finance as a secondary quote provider?

**Comment by HarryPublic** [comment]
Not sure yahoo also provides greeks ... oh but looked at your code ... you have implemented black scholes so its just a question of getting the data and feeding the BS model. Maybe not today, but I might send out a pull request over the next couple of weeks. Definitely doable.

**Comment by mcdallas** [comment]
@baerrus quotes from Yahoo Finance are delayed though.

**Comment by HarryPublic** [comment]
Looks like YF will not work. The recently changed / broke their API and the
whole pandas community is unable to fix it. I only need delayed data - I
want to run my code on my portfolio and identify and email me the most
outlier positions (most at risk, most safe) and it does not matter much if
the data is a bit delayed. I find that much better than going through my
position list manually (it is somewhat big).

**Comment by nicad** [comment]
is it the same issue that ETF options are not available:
`
>> import wallstreet
>>> s = Stock('SPY')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Stock' is not defined
>>> s = wallstreet.Stock('SPY')
>>> s.price
215.97
>>> p = wallstreet.Put('SPY')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXX/imports/wallstreet/wallstreet/wallstreet.py", line 143, in __init__
    super().__init__(quote, **kw)
  File "/Users/XXX/imports/wallstreet/wallstreet/wallstreet.py", line 107, in __init__
    raise LookupError('No options listed for this stock.')
LookupError: No options listed for this stock.
>>> p = wallstreet.Put('GOOG')
No options listed for given date, using 21-10-2016 instead
>>> p = wallstreet.Put('EFA')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXX/imports/wallstreet/wallstreet/wallstreet.py", line 143, in __init__
    super().__init__(quote, **kw)
  File "/Users/XXX/imports/wallstreet/wallstreet/wallstreet.py", line 107, in __init__
    raise LookupError('No options listed for this stock.')
LookupError: No options listed for this stock.
>>>
`

also don't need real-time

**Comment by mcdallas** [comment]
@nicad Yes. Apparently GF doesn't provide option chains for ETFs.

**Comment by baerrus** [comment]
GF also started skipping whole options series arbitrarily. For example take a look at SBUX. Today it shows only Oct21, Jan17 and Jan18 expirations. SBUX has weeklies as well as Nov and Dec series listed.

**Comment by HarryPublic** [comment]
I think most of the options data now is for fee, but even for fee there is
no simple API to pull those out.

**Comment by nicad** [comment]
Would https://query2.finance.yahoo.com/v7/finance/options/SPY be a valid replacement ?

**Comment by HarryPublic** [comment]
this is fantastic, but my personal interest is exclusively in index options
(SPX, RUT, NDX), so no. Not for me.

**Comment by mcdallas** [comment]
I have added Yahoo Finance as a secondary source. You can use it by passing the source='yahoo' parameter but keep in mind that it might be delayed. It is not up on PyPI yet cause there might be some bugs. You can pip install by passing the url or clone the repo.
