### ISSUE TITLE
Source='google' option fails

### ISSUE THREAD

**Issue by josiahlund** [mcdallas/wallstreet#34]
It appears that attempting to call any valid ticker with the source='google' option fails. Line 168 of wallstreet.py is a "catch all" exception that is resulting in a LookupError being thrown even when a valid symbol is passed. Just spending a few minutes trying to find the source on the issue leads me to believe that the response text from line 162 is html rather than something that json.loads() can parse.

**Comment by mcdallas** [comment]
Yes google finance API has been discontinued for a while now, the old google code needs to be removed.

**Comment by josiahlund** [comment]
Is there a commit associated with this issue being closed? It seems the issue still exists and should not yet be closed.

**Comment by mcdallas** [comment]
Other than google bringing back Google Finance how can this be fixed?

**Comment by josiahlund** [comment]
I would say removing the non-functioning code from the code base.
