### ISSUE TITLE
Getting a 403 Client Error for any request

### ISSUE THREAD

**Issue by pushkatel** [mcdallas/wallstreet#36]
Any stock, call, put requesting is returning with
`403 Client Error: Forbidden for url: https://query2.finance.yahoo.com/v7/finance/options/[STOCK TICKER]`

Anyone else seeing this or know of a workaround?

**Comment by mcdallas** [comment]
Yes you need to upgrade to the latest version via `pip install —upgrade wallstreet`

**Comment by pushkatel** [comment]
Wow. I feel particularily silly today. Thanks!
