### ISSUE TITLE
"No options listed for stock", but it exists in yahoo finance

### ISSUE THREAD

**Issue by javioden** [mcdallas/wallstreet#38]
First of all, thank you so much for this amazing library. It is really useful and easy to use. 

I have noticed a problem that happens from time to time, a LookUp error in "normal" stocks. For example, as of now (Dec 1st) if you try to search for OTIS options...
<img width="984" alt="E1  No OTIS options on Dic 1st" src="https://user-images.githubusercontent.com/69435022/144291460-5cb4f469-236c-4c6d-a006-3fb34928d469.png">
Sometimes yahoo finance doesn´t have options data (it happens especially with options on indices like ^SPX), but this is not the case this time:
<img width="982" alt="E1  But they exists in YF" src="https://user-images.githubusercontent.com/69435022/144291728-75ab5082-f84a-4015-93be-1653b7380585.png">

Do you know why this happens?

Thank you again for your great work

**Comment by mcdallas** [comment]
hey @javioden, could you try `Put(‘OTIS’).expirations` and see if you get any results?

**Comment by javioden** [comment]
hey @mcdallas, sorry for the late response. 
it only happens from time to time, I have tried `Put(‘OTIS’).expirations` and everything seems to work fine now. If I encounter this error again I will try to search for its expirations and create a new issue
Thanks again
