### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://query2.finance.yahoo.com/v7/finance/options/AAPL

### ISSUE THREAD

**Issue by echoecho171** [mcdallas/wallstreet#40]
the link https://query2.finance.yahoo.com/v7/finance/options/ now is stop using?
when i run the examples,show this error

**Comment by mcdallas** [comment]
You might need to update to the latest version, see https://github.com/mcdallas/wallstreet/issues/36
