### ISSUE TITLE
Import Failure

### ISSUE THREAD

**Issue by EigenEngineer** [mcdallas/wallstreet#5]
The statement "import wallstreet" returns an error message.

 " File "C:\Anaconda2\lib\site-packages\wallstreet\wallstreet.py", line 125
  raise ValueError('Possible expiration dates for this stock are:', self.expirations) from None"

**Comment by EigenEngineer** [comment]
perhaps this is not downward compatible with python 2

**Comment by mcdallas** [comment]
Yes, the "raise Exception from None" syntax only works in Python 3. I haven't really tested this library with Python 2.
