### ISSUE TITLE
Issue with wallstreet module

### ISSUE THREAD

**Issue by rsmileyc** [mcdallas/wallstreet#8]
I am trying to get Call and Put data for Options that I know exist for several stocks.  I get the following data output using wallstreet 0.1.5: No options listed for given date, using 16-06-2017 instead.  I am trying to get Call and Put option values for expiration dates of 19-05-2017 for AAPL and GOOGL.  Can you help me extract this data using wallstreet?

**Comment by mcdallas** [comment]
That's because the 16/06/2017 options don't appear on Google Finance. If you download version 0.2 (by cloning the repo) you can use Yahoo Finance instead.

```
In [1]: from wallstreet import Call, Put

In [2]: apple = Call('AAPL', d=19, m=5, y=2017, source='yahoo')

In [3]: apple.strikes
Out[3]:
(2.5, 10, 20, 35, 50, 70, 80, 85, 90, 95, 100, ... )
```

**Comment by rsmileyc** [comment]
Are you talking about wallstreet 0.2 or Yahoo-Finance 0.2?  I cannot find either one.

**Comment by mcdallas** [comment]
I am talking about wallstreet 0.2. Assuming you have git installed, type:

    pip install git+https://github.com/mcdallas/wallstreet.git
